### ISSUE TITLE
Is this a README or a Lab?

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/forks-and-clones-readme#15]
`In the terminal (accessed through the 'Sandbox' or Learn IDE), we need to run the git clone command. It takes the URL we just copied as an argument, like so:`

This lab makes reference to using the Sandbox or the IDE but there is no button for the Sandbox or IDE

**Comment by drakeltheryuujin** [comment]
Hi @FreeBreadsticks,

This is a README. This lesson has been updated and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
