### ISSUE TITLE
the instructions never seem to tell you to connect it to a remote repo

### ISSUE THREAD

**Issue by RaffiSapire** [learn-co-curriculum/forks-and-clones-readme#5]
the instructions never seem to tell you to connect it to a remote repo

**Comment by AnnJohn** [comment]
hi @RaffiSapire not sure exactly what you mean? Could you elaborate a little bit more? Thanks!

**Comment by vicfriedman** [comment]
closing this issue unless you're still having issues @RaffiSapire
